### ISSUE TITLE
Adding AI to IKD

### ISSUE THREAD

**Issue by danboid** [nickbild/combat#2]
Hi Nick

I have written a remake of Combat called IKD for the open source Uzebox games console.

https://github.com/danboid/IKD

IKD not only my first Uzebox game but it is also my first C program. It's most notable feature is its music as its one of the best chiptunes on the platform, Rob Hubbard liked our remake of his C64 Commando theme used for the IKD title screen.

Like Combat, IKD is currently 2 player only and the most requested feature is adding AI to make it playable as a one player game.

The Uzebox is similar to the 2600 in that it also has no video buffer but it has a little bit more memory and a much faster CPU.

It'd be great if you could port your solution to IKD or otherwise could you suggest how I might add some half decent AI as a beginner programmer? I suppose the AI at its most basic level has to turn the tank to face the player and has to be able to navigate a maze to get within shooting range. I can then make it shoot at frequent randomised intervals.

Thanks 

Thanks

**Comment by nickbild** [comment]
Hi Dan,

I used AI tank control for the fun of building it into a 4KB Atari 2600
cart. It is not the most practical solution, however. I think you would
have a much easier time writing a rules-based algorithm that tells the tank
what to do.

Nick
